name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: ubuntu-22.04
    container:
      image: openjdk:${{ matrix.java }}-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3 # Install java to run gradle with
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and Test
        run: ./gradlew build --stacktrace
        env:
          JDK_VERSION: ${{ matrix.java }}
